version: '3.1'
services:
  db:
    image: mysql
    container_name: animes_registration_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - animesre_gistration_data:/var/lib/mysql

volumes:
  animesre_gistration_data: