server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: animes-registration
  datasource:
    url: jdbc:mysql://localhost:3309/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
#        type: trace

management:
  endpoints:
    web:
      exposure:
        #          include: "*"
        include: info, health, metrics, prometheus
  info:
    env:
      enabled: true
info:
  app: Animes Resgistration
  website: https://linkedin.com/in/viniciusvbs/
  githubPersonal: https://github.com/viniciusvilasbs